# Generated by Django 6.0.4 on 2026-06-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crop_factors_favouring_crop_layman_knowledge_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'verbose_name_plural': 'Farms'},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name_plural': 'Farmers'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name_plural': 'Managers'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AddField(
            model_name='crop',
            name='preferred_regions',
            field=models.TextField(blank=True, help_text='Ugandan regions where this crop thrives'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(choices=[('loamy', 'Loamy'), ('sandy', 'Sandy'), ('clayey', 'Clayey'), ('silty', 'Silty')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(choices=[('Kampala', 'Kampala'), ('Gulu', 'Gulu'), ('Entebbe', 'Entebbe'), ('Jinja', 'Jinja'), ('Mbarara', 'Mbarara'), ('Masaka', 'Masaka'), ('Mbale', 'Mbale'), ('Arua', 'Arua'), ('Lira', 'Lira'), ('Fort Portal', 'Fort Portal'), ('Mukono', 'Mukono'), ('Soroti', 'Soroti'), ('Hoima', 'Hoima'), ('Kitgum', 'Kitgum'), ('Mubende', 'Mubende'), ('Other', 'Other Ugandan Location')], db_index=True, default='Kampala', max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
