# Generated by Django 6.0.4 on 2026-06-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_crop_options_alter_farm_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('best_regions', models.TextField(blank=True)),
                ('expected_income', models.CharField(blank=True, max_length=100)),
                ('housing_requirements', models.TextField(blank=True)),
                ('feeding_guide', models.TextField(blank=True)),
                ('health_tips', models.TextField(blank=True)),
                ('market_info', models.TextField(blank=True)),
                ('best_for_farmer_type', models.CharField(choices=[('smallholder', 'Smallholder Subsistence Farmer'), ('commercial', 'Commercial/Semi-commercial Farmer')], default='smallholder', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Livestock',
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='best_for_farmer_type',
            field=models.CharField(choices=[('smallholder', 'Smallholder Subsistence Farmer'), ('commercial', 'Commercial/Semi-commercial Farmer')], default='smallholder', max_length=50),
        ),
        migrations.AddField(
            model_name='crop',
            name='market_potential',
            field=models.TextField(blank=True, help_text='Market price insights for this crop in Uganda'),
        ),
        migrations.AddField(
            model_name='crop',
            name='pest_disease_management',
            field=models.TextField(blank=True, help_text='Local pest/disease control methods'),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_instructions',
            field=models.TextField(blank=True, help_text='Step-by-step planting guide'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_type',
            field=models.CharField(choices=[('smallholder', 'Smallholder Subsistence Farmer'), ('commercial', 'Commercial/Semi-commercial Farmer')], default='smallholder', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='market_insights',
            field=models.TextField(blank=True, help_text='Market price insights for Uganda'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('crop', 'Crop'), ('livestock', 'Livestock')], default='crop', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='soil_analysis',
            field=models.TextField(blank=True, help_text='Soil suitability analysis'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='weather_outlook',
            field=models.TextField(blank=True, help_text='Local weather & climate data'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(choices=[('Kampala', 'Kampala'), ('Gulu', 'Gulu'), ('Entebbe', 'Entebbe'), ('Jinja', 'Jinja'), ('Mbarara', 'Mbarara'), ('Masaka', 'Masaka'), ('Mbale', 'Mbale'), ('Arua', 'Arua'), ('Lira', 'Lira'), ('Fort Portal', 'Fort Portal'), ('Mukono', 'Mukono'), ('Soroti', 'Soroti'), ('Hoima', 'Hoima'), ('Kitgum', 'Kitgum'), ('Mubende', 'Mubende'), ('Kabale', 'Kabale'), ('Kasese', 'Kasese'), ('Iganga', 'Iganga'), ('Other', 'Other Ugandan Location')], db_index=True, default='Kampala', max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.crop'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='fertilizer_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='irrigation_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='pesticide_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.livestock'),
        ),
    ]
